# ===========================
# Project & Paths
# ===========================
project:
  name: breast_cancer_ai_helper
  version: "0.1.0"

paths:
  # Root is the repository root (where this file lives)
  raw_root: "data/01_raw"
  raw_vocab_dir: "data/01_raw/VOCAB"
  raw_structured_dir: "data/01_raw/STRUCTURED"
  raw_qualitative_dir: "data/01_raw/QUALITATIVE"
  dict_dir: "data/01_raw/DICTIONARY"

  # Outputs
  interim_dir: "data/02_interim"
  processed_dir: "data/03_processed"
  logs_dir: "logs"

outputs:
  compiled_vocab_csv: "data/03_processed/compiled_vocab.csv"
  compiled_vocab_jsonl: "data/03_processed/compiled_vocab.jsonl"
  compiled_vocab_parquet: "data/03_processed/compiled_vocab.parquet"
  compiled_vocab_stats: "data/03_processed/compiled_vocab_stats.json"

# ===========================
# File Discovery
# ===========================
discovery:
  # Which files to scan inside VOCAB (and elsewhere when scripts support it)
  include_globs:
    - "**/*.csv"
    - "**/*.tsv"
    - "**/*.txt"
    - "**/*.xlsx"
    - "**/*.xls"
    - "**/*.json"
    - "**/*.jsonl"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.gct"      # gene expression matrices
    - "**/*.gmt"      # gene sets / pathways
    - "**/*.seg"      # copy-number segments
    - "**/*.vcf"
    - "**/*.vcf.gz"
  exclude_globs:
    - "**/__MACOSX/**"
    - "**/.ipynb_checkpoints/**"
    - "**/README.md"
    - "**/*.md"
    - "**/tests/**"
    - "**/*.log"
    - "**/*.pdf"      # qualitative PDFs are handled by a different script
    - "**/*.png"
    - "**/*.jpg"
    - "**/*.jpeg"

# ===========================
# Parsing Rules
# ===========================
parsing:
  # Default encodings to try in order
  encodings: ["utf-8", "utf-8-sig", "latin-1", "cp1252"]

  # Delimiter guess priority by extension
  delimiter_by_ext:
    csv: ","
    tsv: "\t"
    txt: "\t"         # most “meta_*.txt” are tab-delimited
    gct: "\t"
    gmt: "\t"
    seg: "\t"
    json: ""
    jsonl: ""
    xlsx: ""
    xls: ""
    vcf: "\t"

  # Some formats have “preamble” rows that must be skipped
  skiprows_by_ext:
    gct: 2            # GCT first two lines are header metadata
    gmt: 0
    seg: 1            # often has a header row starting with 'ID'—readers will also detect
    vcf: 0            # handled by a dedicated reader in other scripts
    default: 0

  # Column names that, if present, are strong pointers for the "term" column
  preferred_term_columns:
    - "symbol"            # HGNC gene symbols
    - "hgnc_symbol"
    - "gene"
    - "gene_symbol"
    - "gene_name"
    - "entrez_gene_id"
    - "ensembl_gene"      # Ensembl (w/ or w/o version)
    - "ensembl_gene_id"
    - "hpo_term"
    - "drug"
    - "drug_name"
    - "compound"
    - "therapy"
    - "pathway"
    - "hallmark"
    - "kegg_pathway"
    - "reactome_pathway"
    - "icd10"
    - "icdo3"
    - "oncotree_code"
    - "oncotree_primary_diagnosis"
    - "cnv_gene"
    - "transcript"
    - "variant_id"

  # If no good column name matches, we can still extract terms by regex
  regex_extractors:
    # Ensembl genes with optional version
    - name: "ensembl_gene"
      pattern: "(ENSG\\d{11}(?:\\.\\d+)?)"
      term_type: "gene"
    # HGNC-like gene symbols (upper-case 2–8 letters/numbers, excludes obvious non-genes)
    - name: "hgnc_symbol"
      pattern: "\\b[A-Z0-9]{2,8}\\b"
      term_type: "gene"
      # We'll still filter with denylist/stopwords
    # DrugBank IDs
    - name: "drugbank_id"
      pattern: "\\bDB\\d{5}\\b"
      term_type: "drug"
    # RSIDs
    - name: "dbsnp_rsid"
      pattern: "\\brs\\d+\\b"
      term_type: "variant"
    # ICD codes (very permissive, rely on later cleaning)
    - name: "icd"
      pattern: "\\b[AC-UV]\\d{2}(?:\\.\\d+)?\\b"
      term_type: "clinical_code"

# ===========================
# Classification (Type Hints)
# → both filename & column-name hints. Case-insensitive substring match.
# ===========================
vocab:
  # If ANY of these substrings appear in a filename (or column), tag with that term_type.
  type_hints:
    gene:
      - "gene"
      - "genes"
      - "hgnc"
      - "symbol"
      - "rna"
      - "rpkm"
      - "tpm"
      - "fpkm"
      - "gct"
      - "transcript"
      - "ensembl"
      - "ccle"
      - "cancer_gene_census"
      - "oncogene"
      - "tumor_suppressor"
      - "driver_mutations"
    drug:
      - "drug"
      - "drugs"
      - "compound"
      - "agent"
      - "therapy"
      - "therapies"
      - "treatment"
      - "fda_approved"
      - "drugbank"
      - "chembl"
      - "name_generic"
      - "moa"
    pathway:
      - "pathway"
      - "hallmark"
      - "kegg"
      - "reactome"
      - "biocarta"
      - "msigdb"
      - "gmt"
      - "gene_set"
    variant:
      - "vcf"
      - "mutation"
      - "mutations"
      - "snv"
      - "indel"
      - "maf"
      - "rsid"
      - "dbsnp"
      - "hgvs"
    copy_number:
      - "cna"
      - "copy_number"
      - "seg"
      - "gistic"
      - "cnv"
    methylation:
      - "methylation"
      - "hm27"
      - "hm450"
      - "methyl"
      - "beta_value"
    expression:
      - "expression"
      - "rsem"
      - "rnaseq"
      - "microarray"
      - "gct"
      - "counts"
      - "tpm"
      - "fpkm"
    proteomics:
      - "proteomics"
      - "rppa"
      - "protein"
      - "phospho"
    clinical:
      - "clinical"
      - "patient"
      - "sample"
      - "phenotype"
      - "er"
      - "pr"
      - "her2"
      - "stage"
      - "grade"
      - "tnm"
      - "oncotree"
      - "icd"
      - "icdo"
      - "outcome"
      - "os"
      - "dfs"
      - "pfs"
      - "treatment_response"
      - "drug_response"
      - "survival"
      - "vital_status"
    biospecimen:
      - "biospecimen"
      - "aliquot"
      - "analyte"
      - "portion"
      - "slide"
      - "tumor_descriptor"
    exposure:
      - "exposure"
      - "smoking"
      - "alcohol"
      - "radiation"
      - "asbestos"
      - "occupational"
      - "environmental"
    imaging:
      - "dsa"
      - "wsi"
      - "radiology"
      - "dicom"
    ontology:
      - "hpo"
      - "go_"
      - "mesh"
      - "efo"
      - "ncit"
      - "so_"
    cell_line:
      - "cell_line"
      - "depmap"
      - "ccle"

  # Term cleaning (remove these exactly if they appear as isolated tokens)
  entity_stopwords:
    - "gene"
    - "genes"
    - "id"
    - "name"
    - "value"
    - "values"
    - "na"
    - "null"
    - "none"
    - "unknown"
    - "sample"
    - "patient"
    - "case"
    - "control"
    - "tumor"
    - "normal"
    - "hg19"
    - "grch37"
    - "grch38"
    - "log2"
    - "chromosome"
    - "chr"
    - "position"
    - "segmean"
    - "start"
    - "end"
    - "pvalue"
    - "qvalue"
    - "ratio"
    - "count"
    - "counts"

  # Deny patterns (drop matches that are obviously not entities)
  entity_deny_regex:
    - "^[\\d\\.]+$"              # pure numbers/decimals
    - "^(true|false)$"           # booleans
    - "^[A-Z]$"                  # single letters
    - "^(and|or|not)$"
    - "^(min|max|avg|mean|std)$"
    - "^(male|female)$"
    - "^rs\\d{1,3}$"             # too small to be meaningful

# ===========================
# Big File Handling
# ===========================
performance:
  engine: "polars"     # default; you can override with CLI --engine pandas
  # Chunk sizes are only used when engine == "pandas"
  pandas_chunk_rows: 200000
  # Memory guard: if free RAM drops below this (MB), the script will switch to streaming
  min_free_mem_mb: 512

# ===========================
# Column Normalization
# (helps later merges)
# ===========================
normalize:
  # Map common aliases to a canonical name
  column_aliases:
    case_id: ["case_id", "sample_id", "patient_id", "submitter_id", "bcr_patient_barcode"]
    gene_symbol: ["symbol", "gene", "gene_symbol", "hgnc_symbol"]
    ensembl_gene_id: ["ensembl", "ensembl_gene", "ensembl_gene_id"]
    drug_name: ["drug", "drug_name", "agent", "therapy", "compound"]
    pathway_name: ["pathway", "gene_set", "hallmark", "kegg_pathway", "reactome_pathway"]
    icd10: ["icd10", "icd_10", "icd"]
    icdo3: ["icdo3", "icd_o_3", "morphology"]
    oncotree_code: ["oncotree_code", "oncotree", "oncotree_primary_diagnosis"]
    effect: ["effect", "consequence", "variant_class"]
    expression_value: ["rpkm", "tpm", "fpkm", "counts", "expression", "value"]
    copy_number_value: ["log2", "seg.mean", "segmean", "cn", "cna_value"]
    methylation_beta: ["beta", "beta_value", "methylation", "mvalue", "m_value"]
    response: ["response", "treatment_response", "best_response", "drug_response"]

# ===========================
# IDs & Crosswalks (optional now, useful later)
# ===========================
ids:
  # If you later download these maps, the merge scripts can resolve to canonical IDs
  hgnc_to_ensembl: "data/01_raw/DICTIONARY/hgnc_to_ensembl.tsv"
  drugbank_to_generic: "data/01_raw/DICTIONARY/drugbank_to_generic.tsv"
  pathway_xwalk: "data/01_raw/DICTIONARY/pathway_xwalk.tsv"
  oncotree_xwalk: "data/01_raw/DICTIONARY/oncotree_xwalk.tsv"
  icd_xwalk: "data/01_raw/DICTIONARY/icd_xwalk.tsv"
